version: "3"

services:
  dbsv_mongo:
    container_name: dbsv_mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo/init/:/docker-entrypoint-initdb.d/
      - /var/opt/mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: user
    logging:
      driver: journald
  # for mitsubishi
  mit_dbsv:
    container_name: mit_dbsv
    image: 0eta0/dbsv:latest
    links:
      - dbsv_mongo
    depends_on:
      - dbsv_mongo
    environment:
      HOST_ADDRESS: swcn20.u-aizu.ac.jp
      DBS_SYSTEM_TYPE: mit
      MDB_MONGO_HOST: dbsv_mongo
      UWSGI_PROCESSES: 2
    logging:
      driver: journald
  # for glove
  glo_dbsv:
    container_name: glo_dbsv
    image: 0eta0/dbsv:latest
    links:
      - dbsv_mongo
    depends_on:
      - dbsv_mongo
    environment:
      HOST_ADDRESS: swcn20.u-aizu.ac.jp
      DBS_SYSTEM_TYPE: glo
      MDB_MONGO_HOST: dbsv_mongo
      UWSGI_PROCESSES: 1
    logging:
      driver: journald
  # for handwriting
  hw_dbsv:
    container_name: hw_dbsv
    image: 0eta0/dbsv:latest
    links:
      - dbsv_mongo
    depends_on:
      - dbsv_mongo
    environment:
      HOST_ADDRESS: swcn20.u-aizu.ac.jp
      DBS_SYSTEM_TYPE: hw
      MDB_MONGO_HOST: dbsv_mongo
      UWSGI_PROCESSES: 1
    logging:
      driver: journald
  # for human activity recognition
  har_dbsv:
    container_name: har_dbsv
    image: 0eta0/dbsv:latest
    links:
      - dbsv_mongo
    depends_on:
      - dbsv_mongo
    environment:
      HOST_ADDRESS: swcn20.u-aizu.ac.jp
      DBS_SYSTEM_TYPE: har
      MDB_MONGO_HOST: dbsv_mongo
      UWSGI_PROCESSES: 1
    logging:
      driver: journald
  # for test
  tes_dbsv:
    container_name: tes_dbsv
    image: 0eta0/dbsv:latest
    links:
      - dbsv_mongo
    depends_on:
      - dbsv_mongo
    environment:
      HOST_ADDRESS: swcn20.u-aizu.ac.jp
      DBS_SYSTEM_TYPE: tes
      MDB_MONGO_HOST: dbsv_mongo
      UWSGI_PROCESSES: 1
    logging:
      driver: journald
  # nginx
  dbsv_nginx:
    container_name: dbsv_nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sites-config/:/etc/nginx/sites-config/:ro
    ports:
      - 8910:8910
    links:
      - mit_dbsv
      - hw_dbsv
      - glo_dbsv
      - har_dbsv
      - tes_dbsv
    depends_on:
      - mit_dbsv
      - glo_dbsv
      - hw_dbsv
      - har_dbsv
      - tes_dbsv
    logging:
      driver: journald
