version: "3"

services:
  dbsv_mongo:
    container_name: dbsv_mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo/init/:/docker-entrypoint-initdb.d/
      - ./mongo/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: user
    # logging:
    #   driver: journald
  # for mitsubishi
  m_dbsv:
    container_name: m_dbsv
    image: 0eta0/dbsv:latest
    links:
      - dbsv_mongo
    depends_on:
      - dbsv_mongo
    environment:
      HOST_ADDRESS: swcn20.u-aizu.ac.jp
      DBS_SYSTEM_TYPE: mit
      MDB_MONGO_HOST: dbsv_mongo
    # logging:
    #   driver: journald
  # for handwriting
  hw_dbsv:
    container_name: hw_dbsv
    image: 0eta0/dbsv:latest
    links:
      - dbsv_mongo
    depends_on:
      - dbsv_mongo
    environment:
      HOST_ADDRESS: swcn20.u-aizu.ac.jp
      DBS_SYSTEM_TYPE: hw
      MDB_MONGO_HOST: dbsv_mongo
    # logging:
    #   driver: journald
  # for human activity recognition
  har_dbsv:
    container_name: har_dbsv
    image: 0eta0/dbsv:latest
    links:
      - dbsv_mongo
    depends_on:
      - dbsv_mongo
    environment:
      HOST_ADDRESS: swcn20.u-aizu.ac.jp
      DBS_SYSTEM_TYPE: har
      MDB_MONGO_HOST: dbsv_mongo
    # logging:
    #   driver: journald
  dbsv_nginx:
    container_name: dbsv_nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sites-config/:/etc/nginx/sites-config/:ro
    ports:
      - 8910:8910
    links:
      - m_dbsv
      - hw_dbsv
      - har_dbsv
    depends_on:
      - m_dbsv
      - hw_dbsv
      - har_dbsv
    # logging:
    #   driver: journald
